name: autonort
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.4

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logoicoapp.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/logoicoapp.png"

flutter_native_splash:
  color: "#3A4F6F"

  android_12:
    color: "#3A4F6F"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animations/
    - assets/images/
    - assets/icon/
    - google_fonts/montserrat_alternates/
